//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public int idProyecto { get; set; }
        public string nombre { get; set; }
        public string cliente { get; set; }
        public string descripcion { get; set; }
    }
}
